### ISSUE TITLE
[Need Help]

### ISSUE THREAD

**Issue by examin** [alertot/detectem#10]
* detectem version: latest
* Python version: 3.6
* Operating System: Windows 10

### Description
After following installation instruction I tried to run detectem with some urls but got this error.
@@
C:\Users\manis>det https://pypi.python.org/pypi/virtualenvwrapper-win
Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python3\Scripts\det.exe\__main__.py", line 9, in <module>
  File "c:\python3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python3\lib\site-packages\detectem\cli.py", line 71, in main
    results = get_detection_results(url, timeout, metadata)
  File "c:\python3\lib\site-packages\detectem\cli.py", line 90, in get_detection_results
    plugins = load_plugins()
  File "c:\python3\lib\site-packages\detectem\plugin.py", line 112, in load_plugins
    loader.load_plugins(pkg)
  File "c:\python3\lib\site-packages\detectem\plugin.py", line 92, in load_plugins
    for module_path in self._get_plugin_module_paths(plugin_dir):
  File "c:\python3\lib\site-packages\detectem\plugin.py", line 57, in _get_plugin_module_paths
    rel_paths = [re.sub(plugin_dir.rstrip('/') + '/', '', fp) for fp in filepaths]
  File "c:\python3\lib\site-packages\detectem\plugin.py", line 57, in <listcomp>
    rel_paths = [re.sub(plugin_dir.rstrip('/') + '/', '', fp) for fp in filepaths]
  File "c:\python3\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\python3\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "c:\python3\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "c:\python3\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "c:\python3\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "c:\python3\lib\sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "c:\python3\lib\sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \p at position 2

**Comment by wang1i** [comment]
Have you resolved it? I met the same problem too

**Comment by csalazar** [comment]
I think it could be related to how different are paths in *nix and Windows (slash and backslashes), but Windows is not supported at the moment. Any PR is welcome!

**Comment by examin** [comment]
I was able to resolve by changing some files (i don't remember exactly) .

But you can try getting Linux environment on windows https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/ .

**Comment by csalazar** [comment]
Yep, Linux environment is the way to go in Windows environments since we don't support Windows.
