### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Sechunt3r** [alertot/detectem#13]
sechunt3r@Spid3r-w3b:~$ det http://google.com
Traceback (most recent call last):
  File "/usr/local/bin/det", line 11, in <module>
    load_entry_point('detectem==0.6.1', 'console_scripts', 'det')()
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectem-0.6.1-py3.6.egg/detectem/cli.py", line 71, in main
    results = get_detection_results(url, timeout, metadata)
  File "/usr/local/lib/python3.6/dist-packages/detectem-0.6.1-py3.6.egg/detectem/cli.py", line 90, in get_detection_results
    plugins = load_plugins()
  File "/usr/local/lib/python3.6/dist-packages/detectem-0.6.1-py3.6.egg/detectem/plugin.py", line 164, in load_plugins
    loader.load_plugins(pkg)
  File "/usr/local/lib/python3.6/dist-packages/detectem-0.6.1-py3.6.egg/detectem/plugin.py", line 154, in load_plugins
    instance = klass()
  File "/usr/local/lib/python3.6/dist-packages/detectem-0.6.1-py3.6.egg/detectem/plugins/generic/wordpress.py", line 19, in __init__
    with open(os.path.join(DATA_DIR, 'wordpress.jl')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/detectem-0.6.1-py3.6.egg/detectem/../data/wordpress.jl

**Comment by wang1i** [comment]
> Hi, got it, I'm going to resolve this in the next few days.

Oh, I have met the same problem, can you tell me how to resolve it?

**Comment by csalazar** [comment]
@Sechunt3r  @wang1i hi, please check with last commit!

**Comment by csalazar** [comment]
I think the issue is resolved.
